[2024-08-28T02:35:41.507+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-28T02:35:41.516+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: paxpe_dag.run_paxpe_notebook manual__2024-08-28T02:35:40.792028+00:00 [queued]>
[2024-08-28T02:35:41.520+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: paxpe_dag.run_paxpe_notebook manual__2024-08-28T02:35:40.792028+00:00 [queued]>
[2024-08-28T02:35:41.521+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-08-28T02:35:41.528+0000] {taskinstance.py:2879} INFO - Executing <Task(PapermillOperator): run_paxpe_notebook> on 2024-08-28 02:35:40.792028+00:00
[2024-08-28T02:35:41.532+0000] {standard_task_runner.py:72} INFO - Started process 145660 to run task
[2024-08-28T02:35:41.534+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'paxpe_dag', 'run_paxpe_notebook', 'manual__2024-08-28T02:35:40.792028+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/paxpe_dag.py', '--cfg-path', '/tmp/tmper2nlypt']
[2024-08-28T02:35:41.536+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask run_paxpe_notebook
[2024-08-28T02:35:41.563+0000] {task_command.py:467} INFO - Running <TaskInstance: paxpe_dag.run_paxpe_notebook manual__2024-08-28T02:35:40.792028+00:00 [running]> on host 88da97e93f39
[2024-08-28T02:35:41.605+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='paxpe_dag' AIRFLOW_CTX_TASK_ID='run_paxpe_notebook' AIRFLOW_CTX_EXECUTION_DATE='2024-08-28T02:35:40.792028+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-28T02:35:40.792028+00:00'
[2024-08-28T02:35:41.606+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-28T02:35:41.612+0000] {execute.py:83} INFO - Input Notebook:  /opt/***/dags/utils/paxpe.ipynb
[2024-08-28T02:35:41.613+0000] {execute.py:84} INFO - Output Notebook: /opt/***/dags/utils/paxpe_log.ipynb
[2024-08-28T02:35:42.637+0000] {clientwrap.py:44} INFO - Executing notebook with kernel: python3
[2024-08-28T02:37:41.129+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/papermill/operators/papermill.py", line 118, in execute
    pm.execute_notebook(
  File "/home/airflow/.local/lib/python3.8/site-packages/papermill/execute.py", line 131, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/papermill/execute.py", line 251, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [18]":
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[18], line 2
      1 # Write DataFrames to temporary tables
----> 2 write_to_postgres(df_retorno_mensal, "temp_retorno_mensal")
      3 write_to_postgres(df_ativas, "temp_captacao_mercado")
      4 write_to_postgres(df_geral, "temp_cadastro")

Cell In[17], line 4, in write_to_postgres(df, table_name, schema_name)
      1 def write_to_postgres(df, table_name, schema_name="paxpestg"):
      2 
      3     # Definir o fuso horário da sessão para UTC-3
----> 4     cursor.execute("SET TIME ZONE 'America/Sao_Paulo';")
      5     conn.commit()
      7     # Fechar a conexão depois de definir o fuso horário

NameError: name 'cursor' is not defined

[2024-08-28T02:37:41.140+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=paxpe_dag, task_id=run_paxpe_notebook, run_id=manual__2024-08-28T02:35:40.792028+00:00, execution_date=20240828T023540, start_date=20240828T023541, end_date=20240828T023741
[2024-08-28T02:37:41.150+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-28T02:37:41.150+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 9 for task run_paxpe_notebook (
---------------------------------------------------------------------------
Exception encountered at "In [18]":
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[18], line 2
      1 # Write DataFrames to temporary tables
----> 2 write_to_postgres(df_retorno_mensal, "temp_retorno_mensal")
      3 write_to_postgres(df_ativas, "temp_captacao_mercado")
      4 write_to_postgres(df_geral, "temp_cadastro")

Cell In[17], line 4, in write_to_postgres(df, table_name, schema_name)
      1 def write_to_postgres(df, table_name, schema_name="paxpestg"):
      2 
      3     # Definir o fuso horário da sessão para UTC-3
----> 4     cursor.execute("SET TIME ZONE 'America/Sao_Paulo';")
      5     conn.commit()
      7     # Fechar a conexão depois de definir o fuso horário

NameError: name 'cursor' is not defined
; 145660)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/papermill/operators/papermill.py", line 118, in execute
    pm.execute_notebook(
  File "/home/airflow/.local/lib/python3.8/site-packages/papermill/execute.py", line 131, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/papermill/execute.py", line 251, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [18]":
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[18], line 2
      1 # Write DataFrames to temporary tables
----> 2 write_to_postgres(df_retorno_mensal, "temp_retorno_mensal")
      3 write_to_postgres(df_ativas, "temp_captacao_mercado")
      4 write_to_postgres(df_geral, "temp_cadastro")

Cell In[17], line 4, in write_to_postgres(df, table_name, schema_name)
      1 def write_to_postgres(df, table_name, schema_name="paxpestg"):
      2 
      3     # Definir o fuso horário da sessão para UTC-3
----> 4     cursor.execute("SET TIME ZONE 'America/Sao_Paulo';")
      5     conn.commit()
      7     # Fechar a conexão depois de definir o fuso horário

NameError: name 'cursor' is not defined

[2024-08-28T02:37:41.182+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-28T02:37:41.186+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
